INSERT INTO `categorias` (`id`,`descricao`) values (1,'Arrefecimento');
INSERT INTO `categorias` (`id`,`descricao`) values (2,'Motor');
INSERT INTO `categorias` (`id`,`descricao`) values (3,'Freios');
INSERT INTO `categorias` (`id`,`descricao`) values (4,'Escapamentos');
INSERT INTO `categorias` (`id`,`descricao`) values (5,'Revisao');
INSERT INTO `categorias` (`id`,`descricao`) values (6,'Troca de Bateria');
INSERT INTO `categorias` (`id`,`descricao`) values (7,'Correias');
INSERT INTO `categorias` (`id`,`descricao`) values (8,'Hidráulica');
INSERT INTO `categorias` (`id`,`descricao`) values (9,'Transmissão');
INSERT INTO `categorias` (`id`,`descricao`) values (10,'Pneus');
INSERT INTO `categorias` (`id`,`descricao`) values (11,'Suspensão');
INSERT INTO `categorias` (`id`,`descricao`) values (12,'Rodas');
INSERT INTO `categorias` (`id`,`descricao`) values (13,'Radiador');
INSERT INTO `categorias` (`id`,`descricao`) values (14,'Freios ABS');
INSERT INTO `categorias` (`id`,`descricao`) values (15,'Ar Condicionado');
INSERT INTO `categorias` (`id`,`descricao`) values (16,'Injeção');
INSERT INTO `categorias` (`id`,`descricao`) values (17,'Airbag');
INSERT INTO `categorias` (`id`,`descricao`) values (18,'Troca de Óleo');
INSERT INTO `categorias` (`id`,`descricao`) values (19,'Chaveiro');
INSERT INTO `categorias` (`id`,`descricao`) values (20,'Alinhamento e Balanceamento');
INSERT INTO `categorias` (`id`,`descricao`) values (21,'Direção');